# Generated by Django 4.0.2 on 2022-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
