# Generated by Django 4.0.2 on 2022-03-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_petuser_user_email_petuser_user_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='NA', max_length=100)),
                ('pet_age', models.IntegerField()),
                ('pet_sex', models.CharField(default='NA', max_length=100)),
                ('pet_breed', models.CharField(default='NA', max_length=100)),
                ('pet_owner', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='petuser',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='user_phone',
            field=models.IntegerField(),
        ),
    ]
