# Generated by Django 4.0.2 on 2022-03-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_pet_pet_age_alter_pet_pet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_owner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='petuser',
            name='user_phone',
            field=models.IntegerField(),
        ),
    ]
