# Generated by Django 4.0.2 on 2022-03-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_petuser_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petuser',
            name='user_phone',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
