# Generated by Django 4.0.2 on 2022-03-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_petuser_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_owner',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
