# Generated by Django 4.0.2 on 2022-03-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_pet_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_age',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
