# Generated by Django 4.0.2 on 2022-03-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_pet_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petuser',
            name='user_email',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
