# Generated by Django 4.0.2 on 2022-03-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_pet_owner_pet_pet_wight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.petuser'),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_note', models.CharField(default='NA', max_length=100)),
                ('task_status', models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.petuser')),
            ],
        ),
    ]
