# Generated by Django 4.0.3 on 2022-03-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_pet_pet_owner_pet_pet_type_calender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='user',
        ),
    ]
