# Generated by Django 4.0.3 on 2022-03-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_calender_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='task_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
