# Generated by Django 4.0.3 on 2022-03-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_calender_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
