# Generated by Django 4.0.3 on 2022-03-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_pet_pet_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='petuser',
            name='user_password',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=200, null=True),
        ),
    ]
