# Generated by Django 4.0.3 on 2022-03-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_petuser_user_password_alter_pet_pet_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_breed',
        ),
    ]
