# Generated by Django 4.0.3 on 2022-03-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_pet_pet_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('reminder_note', models.CharField(default='NA', max_length=100)),
                ('reminder_status', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=200, null=True)),
            ],
        ),
    ]
