# Generated by Django 4.0.3 on 2022-03-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_breed',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_note',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
