# Generated by Django 4.0.3 on 2022-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_pet_pet_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_title', models.TextField()),
                ('information_artical', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_time',
        ),
    ]
