# Generated by Django 4.0.3 on 2022-03-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_reminder_reminder_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='information_artical',
            new_name='artical',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='information_title',
            new_name='title',
        ),
    ]
