# Generated by Django 4.0.3 on 2022-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_pet_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_birth',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
