# Generated by Django 4.0.3 on 2022-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_remove_pet_pet_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
