# Generated by Django 4.0.3 on 2022-03-11 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_pet_pet_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_wight',
        ),
        migrations.AlterField(
            model_name='calender',
            name='task_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='Male', max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], default='Dog', max_length=200),
        ),
    ]
