# Generated by Django 4.0.3 on 2022-03-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_pet_pet_wight_alter_calender_task_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_weight',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
