# Generated by Django 4.0.3 on 2022-03-11 23:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_pet_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.petuser'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='task_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_status',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], max_length=200, null=True),
        ),
    ]
