# Generated by Django 4.0.3 on 2022-03-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_remove_reminder_reminder_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_feed',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_walk',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=200),
        ),
    ]
