# Generated by Django 4.0.3 on 2022-03-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_rename_artical_information_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='category',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], default='Dog', max_length=200),
        ),
    ]
