# Generated by Django 4.0.3 on 2022-03-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_information_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
