# Generated by Django 4.0.3 on 2022-03-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_alter_pet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_heroid',
            field=models.CharField(default='Pet<django.db.models.fields.AutoField>', max_length=100),
        ),
    ]
