# Generated by Django 4.0.3 on 2022-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_pet_pet_heroid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_heroid',
            field=models.CharField(default='Pet', max_length=100),
        ),
    ]
