# Generated by Django 4.0.3 on 2022-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_remove_pet_pet_breed_remove_pet_pet_heroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
