# Generated by Django 4.0.3 on 2022-03-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_information_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
