# Generated by Django 4.0.3 on 2022-03-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_alter_information_article_image_alter_pet_pet_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='info_images/'),
        ),
    ]
