# Generated by Django 4.0.3 on 2022-03-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_remove_information_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='article_image',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
