# Generated by Django 3.2.12 on 2022-03-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('audio', models.FileField(upload_to='')),
            ],
        ),
    ]
