# Generated by Django 3.2.12 on 2022-03-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='teach',
            field=models.TextField(default='NA'),
        ),
    ]
