# Generated by Django 3.2.12 on 2022-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_command_teach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='command_id',
        ),
        migrations.AlterField(
            model_name='command',
            name='audio',
            field=models.FileField(default='NA', upload_to=''),
        ),
    ]
