# Generated by Django 3.2.12 on 2022-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_remove_pet_pet_pic_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_pic_base64',
            field=models.BinaryField(default=b'\x08'),
        ),
    ]
