# Generated by Django 3.2.12 on 2022-03-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
