# Generated by Django 3.2.12 on 2022-03-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_remove_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_pic_base64',
        ),
    ]
