# Generated by Django 4.0.3 on 2022-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_remove_information_article_image_alter_pet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='info_images/'),
        ),
    ]
