# Generated by Django 3.2.12 on 2022-03-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_calender_task_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='task_d',
            new_name='task_date',
        ),
    ]
