# Generated by Django 3.2.12 on 2022-03-17 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_rename_task_d_calender_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='task_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
