# Generated by Django 3.2.12 on 2022-03-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_alter_calender_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
