# Generated by Django 4.0.3 on 2022-03-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_alter_calender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(default='NA', max_length=300),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_owner',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='backend.petuser'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='Male', max_length=300),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], default='Dog', max_length=300),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_weight',
            field=models.CharField(default='NA', max_length=300),
        ),
    ]
