# Generated by Django 3.2.12 on 2022-03-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_alter_calender_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='task_date',
            new_name='event_day',
        ),
        migrations.RenameField(
            model_name='calender',
            old_name='task_note',
            new_name='event_detail',
        ),
        migrations.RenameField(
            model_name='calender',
            old_name='task_status',
            new_name='event_status',
        ),
    ]
