# Generated by Django 3.2.12 on 2022-03-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_auto_20220319_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='event_day',
            new_name='task_date',
        ),
        migrations.RenameField(
            model_name='calender',
            old_name='event_detail',
            new_name='task_note',
        ),
        migrations.RenameField(
            model_name='calender',
            old_name='event_status',
            new_name='task_status',
        ),
    ]
