# Generated by Django 4.0.3 on 2022-03-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_alter_pet_pet_name_alter_pet_pet_owner_and_more'),
        ('backend', '0072_auto_20220319_1247'),
    ]

    operations = [
    ]
