# Generated by Django 4.0.3 on 2022-03-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_alter_pet_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petuser',
            name='user_phone',
        ),
    ]
