# Generated by Django 3.2.12 on 2022-03-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_merge_20220320_1856'),
        ('backend', '0075_remove_petuser_user_phone'),
    ]

    operations = [
    ]
