# Generated by Django 3.2.12 on 2022-03-30 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_petuser_ally_colourblind_petuser_ally_darkmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(default=datetime.date(2022, 3, 30)),
        ),
    ]
