# Generated by Django 4.0.3 on 2022-04-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_petowner_reminder_feed_petowner_reminder_walk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
