# Generated by Django 3.2.12 on 2022-04-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_calender_pet_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calender',
            new_name='Calendar',
        ),
        migrations.AlterField(
            model_name='petowner',
            name='ally_darkMode',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=1),
        ),
    ]
