# Generated by Django 3.2.12 on 2022-04-02 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_auto_20220402_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
    ]
