# Generated by Django 3.2.12 on 2022-04-02 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0084_alter_pet_pet_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally_textSize', models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large')], default='m', max_length=3)),
                ('ally_darkMode', models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=1)),
                ('ally_colourBlind', models.CharField(choices=[('None', 'None'), ('Protanopia', 'Protanopia'), ('Protanomaly', 'Protanomaly'), ('Deuteranopia', 'Deuteranopia'), ('Deuteranomaly', 'Deuteranomaly'), ('Tritanopia', 'Tritanopia'), ('Tritanomaly', 'Tritanomaly'), ('Achromatopsia', 'Achromatopsia')], default='None', max_length=200)),
                ('reminder_walk', models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=200)),
                ('reminder_feed', models.CharField(choices=[('1', '1'), ('0', '0')], default='0', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
