# Generated by Django 3.2.12 on 2022-04-02 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0085_userextension'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtension',
            new_name='PetOwner2',
        ),
    ]
