# Generated by Django 3.2.12 on 2022-04-02 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0086_rename_userextension_petowner2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner2',
            name='id',
        ),
        migrations.AlterField(
            model_name='petowner2',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
