# Generated by Django 4.0.3 on 2022-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_remove_pet_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_owner',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='backend.petowner2'),
        ),
    ]
