# Generated by Django 4.0.3 on 2022-04-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_pet_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_owner',
        ),
    ]
