# Generated by Django 4.0.3 on 2022-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_calendar_user_pet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
    ]
