# Generated by Django 3.2.12 on 2022-04-04 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_calendar_user_pet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(default=datetime.date(2022, 4, 4)),
        ),
    ]
