# Generated by Django 3.2.12 on 2022-04-18 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_alter_pet_pet_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(default=datetime.date(2022, 4, 18)),
        ),
    ]
