# Generated by Django 3.2.12 on 2022-04-27 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_alter_pet_pet_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='task_status',
            new_name='isChecked',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='task_note',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='task_date',
        ),
        migrations.AddField(
            model_name='calendar',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
    ]
