# Generated by Django 3.2.12 on 2022-04-27 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_auto_20220427_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
